### ISSUE TITLE
Support for MantisBT 2.10 or higher?

### ISSUE THREAD

**Issue by cbspencer66** [mantisbt-plugins/MantisKanban#10]
Hi,

Do you have any plans to make MantisKanban work for MantisBT 2.10 or higher?

**Comment by AntonFix** [comment]
Hello. Any news?

**Comment by dregad** [comment]
Supporting MantisBT > 1.2 requires non-negligible refactoring, to move from projax API to REST API. 

I do not have the time or interest to do this, but will gladly merge any pull request.

**Comment by CasN** [comment]
New version is now available
