### ISSUE TITLE
[BUG] Icons/Images/etc not working

### ISSUE THREAD

**Issue by terinfire** [mantisbt-plugins/MantisKanban#11]
There are a few spots in the code where you're not following (presumably?) the MantisBT 2.x way of doing things to leverage the plugin files appropriately.

I manually corrected on my end (didn't notice till I deployed otherwise I'd have forked/PR'd for you -- thank you for updating the plugin to 2.0, by the way!) on the server.  The image for updating the item is broken unless you use:

`<img border="0" src="/plugin_file.php?file=MantisKanban/pencil.png" alt="Update">`

Before it was something like /plugin/MantisKanban/images/pencil.png or something like that.

You applied it correctly for the CSS, but maybe forgot to update a few of the other images/links after the fact?

**Comment by CasN** [comment]
I cannot replay your issue, on my end withi mantis 2.26 it is working nicely.
