### ISSUE TITLE
[BUG] Installation error

### ISSUE THREAD

**Issue by T9RB** [mantisbt-plugins/MantisKanban#12]
Mantis version: 2.26.1
PHP: 8.2.12
MySQL: 10.4.32, 10.4.32-MariaDB.

When installing, it produces error: #1062: Duplicate entry 'MantisKanban' for key 'PRIMARY', request: INSERT INTO mantis_plugin_table ( basename, enabled ) VALUES ( ?, ? ).  There is no duplicate in the "plugins" table before installation.
What to do with it?

**Comment by CasN** [comment]
This I cannot explain. The message from the Database is clear.
Please remove plugin, check the databasetable mantis_plugin_table  again and remove any entry from MantisKanban.
Also check Mantis_config_table and remove any entry from MantisKanban.
Restart MySQL and install plugin again.
