### ISSUE TITLE
Unable to activate Mantis Kanban  on MantisBT v2.26.2 (  unmet dependencies )

### ISSUE THREAD

**Issue by art1988** [mantisbt-plugins/MantisKanban#14]
Hi !

I've just installed Mantis Kanban 1.2 and jQuery Library 1.11.1 ( from https://github.com/mantisbt-plugins/jquery ) and in Manage -> **Plugins tab it says: "MantisBT Core 1.2.0  jQuery Library 1.6.2" - unmet dependencies.**

**I have:**
MantisBT Version             	2.26.2
Database Schema Version	211
PHP Version	                        8.2.12
Database Driver	                mysqli
Database Version, Description	10.4.32, 10.4.32-MariaDB

Could you please advise how to resolve this issue ?
I really want that kanban board up and running on my mantis :)

![mantis_kanban](https://github.com/mantisbt-plugins/MantisKanban/assets/38325798/ee6aafa7-cb2d-4d85-b3fd-2de8c980f570)

**Comment by CasN** [comment]
please download the correct version from here https://github.com/mantisbt-plugins/MantisKanban/tree/MantisBT2.x

**Comment by art1988** [comment]
That was exactly that repository that I've cloned.
Issue persist.

**Comment by CasN** [comment]
You downloaded the wrong one (https://github.com/mantisbt-plugins/MantisKanban/tree/master ), please follow the libk above.

**Comment by art1988** [comment]
Could you please give correct URL for `git clone` command ?

**Comment by CasN** [comment]
The clone command is indeed not correct, suggest ou download the code with this url:
https://github.com/mantisbt-plugins/MantisKanban/archive/refs/heads/MantisBT2.x.zip

**Comment by art1988** [comment]
It worked.
But all I see is:
![kb](https://github.com/mantisbt-plugins/MantisKanban/assets/38325798/1a7c03a9-ca9c-491a-a0ba-695f3e9887cd)

Are there any options to add issues on board ?
