### ISSUE TITLE
Not working with Mantis 2.26

### ISSUE THREAD

**Issue by thusser** [mantisbt-plugins/MantisKanban#17]
Is this supposed to work with Mantis 2.26? After installing the plugin, all I see on the Kanban page are the headers ("Kanban Board", "Combined", "Overview"), and nothing else. In the dev tools I see some errors about "Refused to load the font [...]" and "Error with Permissions-Policy header: Unrecognized feature: 'browsing-topics'.". Could this be related with the jQuery plugin, which is not installable anymore in Mantis 2.26?

**Comment by CasN** [comment]
Not sure if you installed the correct plugin. Looks like you installed the old one for version 1.x.
Please gei it from here (after removing the current one):
https://github.com/mantisbt-plugins/MantisKanban/tree/MantisBT2.x
