### ISSUE TITLE
Kanban not filtering / steps to configure

### ISSUE THREAD

**Issue by wego21** [mantisbt-plugins/MantisKanban#22]
Hello I tried to use your kanban board, I have set my groups, added also the Tags/statuses that I am using. I assign the tag to the case or set proper status but in the board I see all the items in every group. Seems that the filtering part does not work or I am missing something - some configuration steps.

Can  you please write steps to configure the board? I am using kanbanbt 2.26.3
![eVgnz5yNlP](https://github.com/user-attachments/assets/3042459a-887b-4da1-86d4-0cbf48bcfeaf)

**Comment by ghost** [comment]
Can you provide a screenshot of the settings screen? That will help me to guide you in the right direction.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mario Pham ***@***.***>
Sent: Wednesday, December 18, 2024 7:27:15 PM
To: mantisbt-plugins/MantisKanban ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mantisbt-plugins/MantisKanban] Kanban not filtering / steps to configure (Issue #22)


Hello I tried to use your kanban board, I have set my groups, added also the Tags/statuses that I am using. I assign the tag to the case or set proper status but in the board I see all the items in every group.
Can you please write steps to configure the board? I am using kanbanbt 2.26.3
eVgnz5yNlP.png (view on web)<https://github.com/user-attachments/assets/3042459a-887b-4da1-86d4-0cbf48bcfeaf>

**Comment by ghost** [comment]
I assume this is no longer an issue.
