### ISSUE TITLE
issue with newer versions 2.24.x and 2.27.x

### ISSUE THREAD

**Issue by n00r-muhammad** [mantisbt-plugins/MantisKanban#23]
after adding [MantisKanban](https://github.com/mantisbt-plugins/MantisKanban) on maintisBT versions 2.24.x and 2.27.x
The Kabana board is not working properly. 
upload plugin folder.
restart host services
attached image 
![kanban-maints](https://github.com/user-attachments/assets/c0c64e21-86e7-4779-bd04-9f113aa0588c)

**Comment by ghost** [comment]
Please provide overview of the settings for this plugin. Bear in mind that you need to define the statuses by their code and not the name

**Comment by n00r-muhammad** [comment]
> Please provide an overview of the settings for this plugin. Bear in mind that you need to define the statuses by their code and not the name

@CasN what settings are you referring to? I have just installed the plugin and I am following these steps https://support.mantishub.com/plug_ins/kanban
I am unable to find post-installation configurations or settings. if any please share link or steps
I have been using mantisBT for 14 years, so there is a lot of data in it.

**Comment by ghost** [comment]
In case you are running Mantis through Mantishub using their Kanban plugin, you need to get support there.
The plugin here (https://github.com/mantisbt-plugins/MantisKanban/tree/MantisBT2.x) is in the open source domain and maintained supported by me.

**Comment by n00r-muhammad** [comment]
thank you for your response, @CasN i am using open-source. since i am trying to install the plugin you're supporting.

**Comment by ghost** [comment]
In that case remove the mantishub plugin (where did you download that one?) and download mine  from the link above.
After installing, you can configure this plugin from the plugin-page. 
Please use statuscodes and not status names to configure your groups.

**Comment by ghost** [comment]
I assume this is resiolved now.
