### ISSUE TITLE
Add support for MantisBT 1.3.x

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/MantisKanban#5]
The plugin currently doesn't support MantisBT 1.3.x.

**Comment by dregad** [comment]
I had a look at the plugin, fixed the system notices you reported to try and understand what it does.

I'm not sure adding 1.3 support is worth my while... The plugin seems somewhat half-baked, and relies on projax API (removed in 1.3) and jQuery plugin, so whatever functionality it uses, would have to be rewritten from scratch.

**Comment by schlos** [comment]
Latest MantisBT version is now 2.8.0:
https://www.mantisbt.org/bugs/changelog_page.php?project=mantisbt&version=2.8.0

**Comment by dregad** [comment]
Unless someone submits a pull request for it, I don't see the point in supporting MantisBT 1.3.

See #10 for 2.x support.
