### ISSUE TITLE
What does this plugin do?

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/MantisKanban#6]
- [ ] The github repo description needs to be entered
- [ ] README could elaborate on the above summary 
  - [ ] Screenshots of the plugin in action

**Comment by dregad** [comment]
Referenced the wrong issue in the commits, sorry.

Still not really sure what this plugin does other than showing an apparently static Kanban board :wink:

**Comment by CasN** [comment]
Please see the latest version, it delivers a Kanban Board.
