### ISSUE TITLE
jQuery-1.6.2 missing

### ISSUE THREAD

**Issue by Gabbalo** [mantisbt-plugins/MantisKanban#7]
Hi

after gitcloning to pluginfolder, all I got in the plugin managing page was "jQuery-1.6.2 missing". After out-commenting the "'jQuery'        => '1.6.2'," line, I was able to install it, but that is probably not the way it goes.

Greets from Bonn

**Comment by dregad** [comment]
Did you install the prerequisite [jQuery plugin](https://github.com/mantisbt-plugins/jquery) ?

**Comment by Gabbalo** [comment]
Nope, I did not do that, as it was not mentioned neither in MantisBT
[Systemrequirements](https://www.mantisbt.org/manual/admin.install.requirements.html), [Pre-install tasks](https://www.mantisbt.org/manual/admin.install.preinstall.html) or [Installation Guide](https://www.mantisbt.org/manual/admin.install.new.html)
nor in the [MantisKanban Usage Guide](https://github.com/mantisbt-plugins/MantisKanban/blob/master/README.md).

Probably one should add this to the install requirements for the plugin in the mentioned README.md ;)

But thanks for the information. I'll try it out later. I guess this issue is solved than and can be closed.

**Comment by dregad** [comment]
> Probably one should add this to the install requirements for the plugin in the mentioned README.md ;)

Probably yes, but at the same time on the plugins management page, it clearly says "jQuery 1.6.2" in the "Dependencies" column, so ;-)
